"""New Migration

Revision ID: 31d74dc33c27
Revises: 8e3459e87c2c
Create Date: 2023-06-07 13:19:31.789289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d74dc33c27'
down_revision = '8e3459e87c2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
