"""New Migration

Revision ID: 8e3459e87c2c
Revises: 9f2f4a5f61e8
Create Date: 2023-06-07 13:01:00.420511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3459e87c2c'
down_revision = '9f2f4a5f61e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
